app = "telegram-bot-d1mxiq"  # ← اسم التطبيق الخاص بك على fly.io

primary_region = "ams"       # ← اختياري، منطقة الاستضافة

[build]
  image = "python:3.12"      # ← يمكنك تغييره أو تركه إذا كنت تستخدم Dockerfile

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
